# 头部导航 Header
menu:
  首页: /
  说说: /shuoshuo/
  归档: /archives/
  #书单: /books/
  收藏: /collections/
  资源: /download/
  简历: /about/
  #指明灯: /schedule/
  #commonweal: /404/ || heartbeat
#rss: /atom.xml

# footer底部显示联系邮箱（在博客配置文件下添加email配置也是一样的效果）
email: '751590426@qq.com'
keywords: "fangyukang,方宇康,康,java,个人博客,方宇康的个人博客"

# 内容 Content
excerpt_link: 继续阅读全文 »
fancybox: true

# 启用social widgets时有效
# 社交widget文本字体，不填写则不显示title
social_title: Follow me
# Social links 社交链接
social:
  github: https://github.com/fangyukang
  csdn: https://qy-bb.blog.csdn.net/
  gitee: https://gitee.com/fangyukang
  email: '751590426@qq.com'

# WeChat 微信公众号二维码url
#wechat_url: http://blog.giscafer.com/static/images/qrcode_giscafer.jpg ## 启用wechat widget才会生效


# Friendly links 友情链接
links:
  我的CSDN: https://qy-bb.blog.csdn.net/

# 侧边栏 Sidebar，目前仅支持right
sidebar: right
# 目录展示位置，有两种选择，post为文章内部右侧；widget为sidebar形式展示，在markdown文件中通过toc:false可以指定某文章不展示目录
content_position: widget
# true目录将会浮动固定位置，false则相反，当且仅当content_position=widget时该设置值有效
content_display_fixed: true

# 文章底部推荐文章数,false关闭
random_posts: 5

widgets:
- wechat
- social
- friendly_link
- post_content
- category
- tagcloud
- recent_posts
- archive
#- links
#- weibo

# 提供以下内置组件
# - post_content      # 文章目录
# - category          # 归类
# - tag               # 标签
# - tagcloud          # 云标签
# - archives          # 归档
# - recent_posts      # 最新文章
# - lastest_comments  # 最新评论
# - hot_comment_posts # 热评文章
# - friendly_link     # 友情链接
# - wechat            # 微信公众号

wechat_url: /images/wx.png
# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
# 分类是否显示文章数量
show_count: true

# 标签云TagClound
# 如果启动，则标签云颜色为随机
# tagcloud_color: true

# MathJax Support
# 设置enable属性为true即可开启mathjax
# per_page如果为true表示所有文章都设置支持mathjax，如果为false，则在需要支持mathjax的文章加上mathjax: true
mathjax:
  enable: false
  per_page: true
  cdn: https://cdn.rawgit.com/mathjax/MathJax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML



# 其他参数
google_analytics:
favicon: /images/touxiang.jpg


# comments 评论插件
# 关闭统一为 false

## 网易云跟帖
### 使用说明 http://cafe.giscafer.com/2017/04/14/gentie-test/
#gentie_productKey: e2fb4051c49842688ce669e634bc983f

## 畅言 (不使用请将appid和appkey都设空或者false)
### 使用说明：http://changyan.kuaizhan.com/static/help/
#changyan_appid: cytqzaKso  ##appid
#changyan_appkey: 619ace2ea93ed9610eb101dc0d88192c  ##appkey
changyan_appid: cytYCbn4s
changyan_appkey: e18ab73896248d40bda4389d7380020f
#changyan_appkey: prod_091466078a4442edce6972c091727b01

## 友言
### 使用说明
### 填写友言用户ID http://www.uyan.cc/sites
#youyan_uid: "2134772"
livere:
  on: false
  livere_uid: MTAyMC80NzEwNC8yMzYwNA==

# gitment
## 教程：https://imsun.net/posts/gitment-introduction/ 网站上进行查看
gitment:
  enable: false #如果不使用则设置false关闭
  #githubID: tuzongxun
  owner: 'tuzongxun' #你的github名称或者id id的获取方式为https://api.github.com/users/forvoid（你的名称）中的id极为github id
  repo: 'tuzongxun.github.io' #你的留言存放的位置 我的是放在我的github的github page上面
  client_id: 'b225cc5e089346e5082e' #Register a new OAuth application https://github.com/settings/applications/new 
  client_secret: '69e3e1c8f672ac3520e3f1798993ed09b3bb55d6'
giteement:
  enable: false  # 是否启用码云评论系统
  # 是否使用官方js(false可以提升访问速度)
  remote: false
  redirect_uri: https://blog.tzxcode.cn   # 应用回调地址(请和配置的第三方应用保持一致)
  # 不能更改(网上开源项目https://github.com/Rob--W/cors-anywhere作者提供的专门用来跨域服务器的配置)
  oauth_uri: https://cors-anywhere.herokuapp.com/https://gitee.com/oauth/token
  giteeID: zhousiwei  # 你的码云账号英文名
  # 存储评论的 repo
  repo: tzxBlog
  gitment_oauth:
    client_id: '768b9981ffd3896c65a4bd5d364362915e509683e4578aa79722a45dfe6e462a'           #client ID
    client_secret: '0cdeb425eff47e4db20f1a282bd4b7b8e1cc19b6b1985538076aaa3ddc737d6c'       #client secret

## disqus
disqus_shortname: false

google_plus:
fb_admins:
fb_app_id:

